//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchPro
    {
        public int ID { get; set; }
        public int PatientID { get; set; }
        public string PicPath { get; set; }
        public string ReNamePic { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<System.DateTime> PosteDate { get; set; }
    }
}
