//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctors.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB : DbContext
    {
        public DB()
            : base("name=DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ItmList> ItmLists { get; set; }
        public virtual DbSet<orditm> orditms { get; set; }
        public virtual DbSet<OrdList> OrdLists { get; set; }
        public virtual DbSet<Shft> Shfts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeList> TypeLists { get; set; }
        public virtual DbSet<Dept> Depts { get; set; }
        public virtual DbSet<EmpHi> EmpHis { get; set; }
        public virtual DbSet<EmpInfo> EmpInfoes { get; set; }
        public virtual DbSet<EmpShft> EmpShfts { get; set; }
        public virtual DbSet<Jop> Jops { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<Mor> Mors { get; set; }
        public virtual DbSet<Punsh> Punshes { get; set; }
        public virtual DbSet<Sal> Sals { get; set; }
        public virtual DbSet<Vac> Vacs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Usr> Usrs { get; set; }
        public virtual DbSet<vcashrp> vcashrps { get; set; }
        public virtual DbSet<vExpList> vExpLists { get; set; }
        public virtual DbSet<vOrdList> vOrdLists { get; set; }
        public virtual DbSet<vDept> vDepts { get; set; }
        public virtual DbSet<vEDJ> vEDJs { get; set; }
        public virtual DbSet<vEmpHi> vEmpHis { get; set; }
        public virtual DbSet<vEmpl> vEmpls { get; set; }
        public virtual DbSet<vEmplon> vEmplons { get; set; }
        public virtual DbSet<vJop> vJops { get; set; }
        public virtual DbSet<vLoanE> vLoanEs { get; set; }
        public virtual DbSet<vMorsE> vMorsEs { get; set; }
        public virtual DbSet<vPunE> vPunEs { get; set; }
        public virtual DbSet<vSalary> vSalaries { get; set; }
        public virtual DbSet<vSalEntry> vSalEntries { get; set; }
        public virtual DbSet<vTSal> vTSals { get; set; }
        public virtual DbSet<vUsrEmp> vUsrEmps { get; set; }
        public virtual DbSet<vVacE> vVacEs { get; set; }
        public virtual DbSet<vURole> vURoles { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<ServList> ServLists { get; set; }
        public virtual DbSet<ShiftList> ShiftLists { get; set; }
        public virtual DbSet<StateList> StateLists { get; set; }
        public virtual DbSet<Vwaitlist> Vwaitlists { get; set; }
    }
}
