//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMedic
    {
        public int ID { get; set; }
        public Nullable<int> Categ { get; set; }
        public Nullable<int> SCateg { get; set; }
        public string EnName { get; set; }
        public string ArName { get; set; }
        public Nullable<int> ItemMinPack { get; set; }
        public string Barcod { get; set; }
        public string Type { get; set; }
        public string Materialact { get; set; }
        public Nullable<decimal> PurPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<int> MinStock { get; set; }
        public Nullable<int> Reord { get; set; }
        public string Experiod { get; set; }
        public Nullable<decimal> PurUnit { get; set; }
        public Nullable<decimal> SellUnit { get; set; }
        public Nullable<decimal> LPur { get; set; }
        public Nullable<decimal> LSell { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
