//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientItemMedic
    {
        public int ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> ItemMedicID { get; set; }
        public string EnName { get; set; }
        public Nullable<int> Dose { get; set; }
        public string DoseName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Period { get; set; }
    }
}
