//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VnextPatient
    {
        public int ShiftID { get; set; }
        public Nullable<int> NextPatient { get; set; }
    }
}
