//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRefundRp
    {
        public int ID { get; set; }
        public string PatientName { get; set; }
        public Nullable<int> Serv { get; set; }
        public string ServName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
